name: timer_app
description: A app to set timer for different tasks.

publish_to: 'none' 

version: 1.0.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.jpg

  fonts:
    - family: Zona Pro
      fonts:
        - asset: assets/fonts/ZonaPro-ExtraBoldDemo.otf
        - asset: assets/fonts/ZonaPro-LightItalicDemo.otf